version: '3.9'

services:
  db:
    image: postgres:latest 
    restart: always
    container_name: garagepotti-services-postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistant storage for database

volumes:
  postgres_data: