export const PERMISSIONS = [
  {
    group: 'ROLES',
    name: 'VIEW ROLES',
    slug: 'VIEW_ROLES',
    description: 'VIEW_ROLES',
  },
  {
    group: 'ROLES',
    name: 'CREATE ROLES',
    slug: 'CREATE_ROLES',
    description: 'CREATE_ROLES',
  },
  {
    group: 'ROLES',
    name: 'UPDATE ROLES',
    slug: 'UPDATE_ROLES',
    description: 'UPDATE_ROLES',
  },
  {
    group: 'ROLES',
    name: 'DELETE ROLES',
    slug: 'DELETE_ROLES',
    description: 'DELETE_ROLES',
  },
  {
    group: 'PERMISSIONS',
    name: 'ATTACH ROLE TO USER',
    slug: 'ATTACH_ROLE_TO_USER',
    description: 'ATTACH_ROLE_TO_USER',
  },
  {
    group: 'PERMISSIONS',
    name: 'DETACH ROLE TO USER',
    slug: 'DETACH_ROLE_TO_USER',
    description: 'DETACH_ROLE_TO_USER',
  },
  {
    group: 'PERMISSIONS',
    name: 'VIEW PERMISSIONS',
    slug: 'VIEW_PERMISSIONS',
    description: 'VIEW_PERMISSIONS',
  },
  {
    group: 'PERMISSIONS',
    name: 'ATTACH PERMISSION TO ROLE',
    slug: 'ATTACH_PERMISSION_TO_ROLE',
    description: 'ATTACH_PERMISSION_TO_ROLE',
  },
  {
    group: 'PERMISSIONS',
    name: 'DETACH PERMISSION TO ROLE',
    slug: 'DETACH_PERMISSION_TO_ROLE',
    description: 'DETACH_PERMISSION_TO_ROLE',
  },
  {
    group: 'USERS',
    name: 'VIEW USERS',
    slug: 'VIEW_USERS',
    description: 'VIEW_USERS',
  },
  {
    group: 'USERS',
    name: 'CREATE USERS',
    slug: 'CREATE_USERS',
    description: 'CREATE_USERS',
  },
  {
    group: 'USERS',
    name: 'UPDATE USERS',
    slug: 'UPDATE_USERS',
    description: 'UPDATE_USERS',
  },
  {
    group: 'PROFILE',
    name: 'VIEW PROFILE',
    slug: 'VIEW_PROFILE',
    description: 'VIEW_PROFILE',
  },
  {
    group: 'PROFILE',
    name: 'UPDATE PROFILE',
    slug: 'UPDATE_PROFILE',
    description: 'UPDATE_PROFILE',
  },
];
